
import { EmployeeType } from "./interface/EmployeeType";

export const employeeTypesData: EmployeeType[] = [
  {
    id: '1',
    name: 'Empleado',
    code: 'EMP',
    status: 'active',
    intelliTime: true,
    intelliLunch: false,
    emailRequired: true,
    signatureRequired: true,
    requiredFields: [
      'Huella', 
      'Rostro', 
      'Perfil De Marcaje', 
      'Estructura', 
      'Contrato', 
      'Fecha Inicial Contrato', 
      'Fecha Final Contrato', 
      'Código', 
      'Cargo', 
      'Departamento', 
      'Sección', 
      'Sede', 
      'Contenedor', 
      'Empresa'
    ],
    checkMethod: 'Biométrico',
    accessLevel: 'Total',
    diningAccess: true,
    overtimeAllowed: true
  },
  {
    id: '2',
    name: 'Proveedor',
    code: 'PRV',
    status: 'active',
    intelliTime: false,
    intelliLunch: false,
    emailRequired: false,
    signatureRequired: false,
    requiredFields: ['Código', 'Empresa', 'Contrato'],
    checkMethod: 'Manual',
    accessLevel: 'Limitado',
    diningAccess: false,
    overtimeAllowed: false
  },
  {
    id: '3',
    name: 'Visitante',
    code: 'VIS',
    status: 'active',
    intelliTime: false,
    intelliLunch: false,
    emailRequired: false,
    signatureRequired: true,
    requiredFields: ['Huella', 'Empresa Visitada', 'Motivo'],
    checkMethod: 'QR',
    accessLevel: 'Visitante',
    diningAccess: false,
    overtimeAllowed: false
  },
];

// Lista de todos los posibles campos disponibles para un tipo de empleado
export const availableFields = [
  'Huella',
  'Rostro',
  'Perfil De Marcaje',
  'Estructura',
  'Contrato',
  'Fecha Inicial Contrato',
  'Fecha Final Contrato',
  'Código',
  'Cargo',
  'Departamento',
  'Sección',
  'Sede',
  'Contenedor',
  'Empresa',
  'Segundo Nombre',
  'Segundo Apellido',
  'Género',
  'Fecha De Nacimiento',
  'País',
  'Estado',
  'Teléfono',
  'Email',
  'Dirección',
  'Ciudad',
  'Zona',
  'Salario',
  'Número De Cuenta',
  'Banco',
  'Tipo De Contrato',
  'Empresa Visitada',
  'Motivo',
  'Hora De Entrada',
  'Hora De Salida'
];